languageMap = {
    "Versioning": "Versionierung",
    "Restore": "Wiederherstellen",
    "Configuration": "Konfiguration",
    "Publish": "Veröffentlichen",
    "New directory": "Neues Verzeichnis",
    "New file": "Neue Datei",
    "File name": "Dateiname",
    "File type": "Dateityp",
    "Access rights": "Zugriffsrechte",
    "Action": "Aktion",
    "Directory": "Verzeichnis",
    "File": "Datei",
    "No Permission": "Keine Zugriffsrechte",
    "Read only": "Schreibgeschützt",
    "Readable and writable": "Zugriff erlaubt",
    "Rename": "Umbennen",
    "Remove": "Entfernen",
    "Close without saving!": "Schließen ohne speichern!",
    "Save": "Speichern",
    "Save and close": "Speichern und schließen",
    "Preview": "Vorschau",
    "Spellcheck": "Rechtschreibprüfung",
    "An error has occurred": "Es ist ein Fehler aufgetreten:",
    "Directory name": "Verzeichnisname",
    "New file name": "Neuer Dateiname",
    "Connection to the server": "Verbindung zum Server",
    "The server could not process the request!": "Der Server konnte die Anfrage nicht berarbeiten!",
    "The changes have been entered into the version management.": "Die Änderungen wurden in die Versionsverwaltung eingepflegt.",
    "The changes could not be entered into the version management!": "Die Änderungen konnte nicht in die Versionsverwaltung eingepflegt werden!",
    "Cancel": "Abbrechen",
    "Take": "Übernehmen",
    "The website has been published.": "Die Website wurde veröffentlich.",
    "The website could not be published!": "Die Website konnte nicht veröffentlicht werden!",
    "Remove": "Entfernen",
    "Save configuration file": "Konfigurationsdatei speichern",
    "The file could not be saved!": "Die Datei konnte nicht gespeichert werden!",
    "Remove file/directory": "Datei/Verzeichnis löschen",
    "The directory or file could not be deleted!": "Das Verzeichnis oder die Datei konnte nicht gelöscht werden!",
    "Rename file/directory": "Datei/Verzeichnis umbenennen",
    "The file or directory could not be renamed!": "Die Datei oder das Verzeichnis konnte nicht umbenannt werden!",
    "Please enter a file name!": "Bitte einen Dateinamen eingeben!",
    "Please enter a directory name!": "Bitte einen Verzeichnisnamen eingeben!",
    "New directory": "Neues Verzeichnis",
    "The directory could not be created!": "Das Verzeichnis konnte nicht angelegt werden!",
    "Rename file": "Datei umbennen",
    "Create": "Anlegen",
    "The directory could not be created!": "Die Datei konnte nicht angelegt werden!",
    "Save file": "Datei speichern",
    "The preview could not be created!": "Die Vorschau konnte nicht erzeugt werden!",
    "Check spelling": "Rechtschreibung überprüfen",
    "Please enter a file name!": "Bitte einen Dateinamen eingeben!",
    "Please enter a commit message!": "Bitte einen Commit-Nachricht eingeben!",
    "Changed on": "Geändert am",
    "The changes have been rolled back.": "Die Änderungen wurden zurückgesetzt.",
    "The changes could not be rolled back!": "Die Änderungen konnten nicht zurückgesetzt werden!",
    "License for": "Lizensiert für",
    "Setup": "Einrichtung",
    "Login": "Login",
    "Enter your login name": "Geben Sie hier Ihre Login ein",
    "Enter your password": "Geben Sie hier Ihre Passwort ein",
    "Password": "Passwort",
    "Change password": "Passwort ändern",
    "Retry password": "Passwort wiederholen",
    "Retry your password": "Wiederholen Sie Ihr Passwort",
    "Easy mode": "Einfacher Modus",
    "Normal mode": "Normaler Modus",
    "Admin mode": "Admin-Modus",
    "Logged in as": "Angemeldet als",
    "in": "im",
    "Add variable": "Variable hinzufügen",
    "Variable name": "Variablenname",
    "Variable value": "Variablenwert",
    "HugoCMS Login": "HugoCMS Anmelden",
    "Submit": "Absenden",
    "Session is expired!": "Sitzung ist abgelaufen!",
    "Use template": "Vorlage verwenden",
    "Save and publish": "Speichern und veröffentlichen",
};

elFinder.prototype.i18.de.messages.errLogout = "Sitzung ist abgelaufen!";
elFinder.prototype.i18.de.messages['cmdcms_edit_md'] = "Im Markdown Editor öffnen";
elFinder.prototype.i18.de.messages['cmdcms_edit_html'] = "Im HTML Editor öffnen";
elFinder.prototype.i18.de.messages['untitled folder'] = 'neuer_ordner';
elFinder.prototype.i18.de.messages['untitled file'] = 'neue_datei.$1';
