languageMap = {
	"Hide Front matter variables": "Front matter variablen verstecken",
	"Saved": "Gespeichert",
	"Show Front matter variables": "Front matter variablen anzeigen",
    "A new project for a different domain are created.": "Ein neues Projekt für eine andere Domain wird erstellt.",
    "Access rights": "Zugriffsrechte",
    "Action": "Aktion",
    "Add variable": "Variable hinzufügen",
    "Admin mode": "Admin-Modus",
    "An error has occurred": "Es ist ein Fehler aufgetreten:",
    "Cancel": "Abbrechen",
    "Cannot overwrite login data!": "Anmeldedaten können nicht überschrieben werden!",
    "Cannot save license key!": "Lizenzschlüssel kann nicht gespeichert werden!",
    "Cannot save licensee data!": "Lizenznehmerdaten können nicht gespeichert werden!",
    "Cannot save template!": "Vorlage kann nicht gespeichert werden!",
    "Change password": "Passwort ändern",
    "Changed on": "Geändert am",
    "Check spelling": "Rechtschreibung überprüfen",
    "Close without saving!": "Schließen ohne speichern!",
    "Configuration": "Konfiguration",
    "Connection to the server": "Verbindung zum Server",
    "Create project*": "Projekt erstellen*",
    "Create": "Anlegen",
    "Directory name": "Verzeichnisname",
    "Directory": "Verzeichnis",
    "Easy mode": "Einfacher Modus",
    "Enter the license key": "Geben Sie den Lizenzschlüssel ein",
    "Enter the name of the licensee": "Geben Sie den Namen des Lizenznehmers ein",
    "Enter the name of the project": "Geben Sie den Projektnamen ein",
    "Enter your login name": "Geben Sie hier Ihre Login ein",
    "Enter your password": "Geben Sie hier Ihre Passwort ein",
    "Error converting configuration to JSON.": "Fehler beim Konvertieren der Konfiguration in JSON.",
    "Error writing updated configuration to file.": "Fehler beim Schreiben der aktualisierten Konfiguration in die Datei.",
    "File name": "Dateiname",
    "File type": "Dateityp",
    "File": "Datei",
    "HugoCMS Login": "HugoCMS Anmelden",
    "in": "im",
    "License file not found!": "Lizenzdatei nicht gefunden!",
    "License for": "Lizensiert für",
    "License key": "Lizenzschlüssel",
    "Licensee": "Lizenznehmer",
    "Logged in as": "Angemeldet als",
    "Login*": "Login*",
    "New directory": "Neues Verzeichnis",
    "New directory": "Neues Verzeichnis",
    "New file name": "Neuer Dateiname",
    "New file": "Neue Datei",
    "New project/ Domain": "Neues Projekt/ Domain",
    "No Permission": "Keine Zugriffsrechte",
    "Normal mode": "Normaler Modus",
    "Password*": "Passwort*",
    "Please enter a commit message!": "Bitte einen Commit-Nachricht eingeben!",
    "Please enter a directory name!": "Bitte einen Verzeichnisnamen eingeben!",
    "Please enter a file name!": "Bitte einen Dateinamen eingeben!",
    "Please enter a file name!": "Bitte einen Dateinamen eingeben!",
    "Please enter a project name!": "Bitte geben Sie einen Projektnamen ein!",
    "Please fill out all fields with an asterisk!": "Bitte füllen Sie alle Felder mit einem Sternchen aus!",
    "Preview": "Vorschau",
    "Project directory already exists!": "Projektverzeichnis existiert bereits!",
    "Project name cannot be empty!": "Projektname darf nicht leer sein!",
    "Project name is missing!": "Projektname fehlt!",
    "Project name": "Projektname",
    "Publish": "Veröffentlichen",
    "Read only": "Schreibgeschützt",
    "Readable and writable": "Zugriff erlaubt",
    "Remove file/directory": "Datei/Verzeichnis löschen",
    "Remove": "Entfernen",
    "Remove": "Entfernen",
    "Rename file": "Datei umbennen",
    "Rename file/directory": "Datei/Verzeichnis umbenennen",
    "Rename": "Umbennen",
    "Restore": "Wiederherstellen",
    "Retry password*": "Passwort wiederholen*",
    "Retry your password": "Wiederholen Sie Ihr Passwort",
    "Revert to the latest restore point. Continue?": "Zurück zum letzten Wiederherstellungspunkt. Fortfahren?",
    "Save and close": "Speichern und schließen",
    "Save and publish": "Speichern und veröffentlichen",
    "Save configuration file": "Konfigurationsdatei speichern",
    "Save file": "Datei speichern",
    "Save": "Speichern",
    "Session is expired!": "Sitzung ist abgelaufen!",
    "Setup": "Setup",
    "Spellcheck": "Rechtschreibprüfung",
    "Submit": "Absenden",
    "Take": "Übernehmen",
    "The changes could not be entered into the version management!": "Die Änderungen konnte nicht in die Versionsverwaltung eingepflegt werden!",
    "The changes could not be rolled back!": "Die Änderungen konnten nicht zurückgesetzt werden!",
    "The changes have been entered into the version management.": "Die Änderungen wurden in die Versionsverwaltung eingepflegt.",
    "The changes have been rolled back.": "Die Änderungen wurden zurückgesetzt.",
    "The configuration file file does not exist.": "Die Konfigurationsdatei existiert nicht.",
    "The configuration file is in the wrong format.": "Die Konfigurationsdatei hat das falsche Format.",
    "The directory could not be created!": "Das Verzeichnis konnte nicht angelegt werden!",
    "The directory could not be created!": "Die Datei konnte nicht angelegt werden!",
    "The directory or file could not be deleted!": "Das Verzeichnis oder die Datei konnte nicht gelöscht werden!",
    "The file could not be saved!": "Die Datei konnte nicht gespeichert werden!",
    "The file or directory could not be renamed!": "Die Datei oder das Verzeichnis konnte nicht umbenannt werden!",
    "The new project cannot created!": "Das neue Projekt kann nicht erstellt werden!",
    "The preview could not be created!": "Die Vorschau konnte nicht erzeugt werden!",
    "The server could not process the request!": "Der Server konnte die Anfrage nicht berarbeiten!",
    "The setup could not be performed!": "Das Setup konnte nicht durchgeführt werden!",
    "The website could not be published!": "Die Website konnte nicht veröffentlicht werden!",
    "The website has been published an the CSS files have been minimized.": "Die Website wurde veröffentlicht und die CSS-Dateien wurden minimiert.",
    "The website has been published.": "Die Website wurde veröffentlich.",
    "Use minimized CSS": "Minimiertes CSS verwenden",
    "Use template": "Vorlage verwenden",
    "Username is missing!": "Benutzername fehlt!",
    "Variable name": "Variablenname",
    "Variable value": "Variablenwert",
    "Versioning": "Versionierung",
    "The setup was successful and can now be completed.": "Das Setup war erfolgreich und kann nun abgeschlossen werden",
    "Continue": "Fortfahren",
    "Change mode": "Modus ändern"
};

elFinder.prototype.i18.de.messages.errLogout = "Sitzung ist abgelaufen!";
elFinder.prototype.i18.de.messages['cmdcms_edit_md'] = "Im Markdown Editor öffnen";
elFinder.prototype.i18.de.messages['cmdcms_edit_html'] = "Im HTML Editor öffnen";
elFinder.prototype.i18.de.messages['untitled folder'] = 'neuer_ordner';
elFinder.prototype.i18.de.messages['untitled file'] = 'neue_datei.$1';
