languageMap = {
    "Versioning": "Versionnement",
    "Restore": "Restaurer",
    "Configuration": "Configuration",
    "Publish": "Publier",
    "New directory": "Nouveau répertoire",
    "New file": "Nouveau fichier",
    "File name": "Nom de fichier",
    "File type": "Type de fichier",
    "Access rights": "Droits d'accès",
    "Action": "Action",
    "Directory": "Répertoire",
    "File": "Déposer",
    "No Permission": "Aucun droit d'accès",
    "Read only": "En lecture seule",
    "Readable and writable": "Accès autorisé",
    "Rename": "Renommer",
    "Remove": "Supprimer",
    "Close without saving!": "Fermer sans sauvegarder !",
    "Save": "Sauvegarder",
    "Save and close": "Sauvegarder et fermer",
    "Preview": "Aperçu",
    "Spellcheck": "Correcteur orthographique",
    "An error has occurred": "Une erreur est survenue :",
    "Directory name": "Nom du répertoire",
    "New file name": "Nouveau nom de fichier",
    "Connection to the server": "Connexion au serveur",
    "The server could not process the request!": "Le serveur n'a pas pu traiter la demande!",
    "The changes have been entered into the version management.": "Les modifications ont été intégrées dans la gestion des versions.",
    "The changes could not be entered into the version management!": "Les modifications n'ont pas pu être intégrées dans la gestion des versions!",
    "Cancel": "Annuler",
    "Take": "Reprendre",
    "The website has been published.": "Le site web a été publié.",
    "The website could not be published!": "Le site web n'a pas pu être publié!",
    "Remove": "Supprimer",
    "Save configuration file": "Sauvegarder le fichier de configuration",
    "The file could not be saved!": "Le fichier n'a pas pu être sauvegardé!",
    "Remove file/directory": "Supprimer le fichier/répertoire",
    "The directory or file could not be deleted!": "Le répertoire ou le fichier n'a pas pu être supprimé!",
    "Rename file/directory": "Renommer le fichier/répertoire",
    "The file or directory could not be renamed!": "Le fichier ou le répertoire n'a pas pu être renommé!",
    "Please enter a file name!": "Veuillez entrer un nom de fichier!",
    "Please enter a directory name!": "Veuillez entrer un nom de répertoire!",
    "New directory": "Nouveau répertoire",
    "The directory could not be created!": "Le répertoire n'a pas pu être créé!",
    "Rename file": "Renommer le fichier",
    "Create": "Créer",
    "The directory could not be created!": "Le répertoire n'a pas pu être créé!",
    "Save file": "Datei speichern",
    "The preview could not be created!": "L'aperçu n'a pas pu être créé!",
    "Check spelling": "Vérifier l'orthographe",
    "Please enter a file name!": "Veuillez entrer un nom de fichier!",
    "Please enter a commit message!": "Veuillez entrer un message de validation!",
    "Changed on": "Changé le",
    "The changes have been rolled back.": "Les changements ont été réinitialisés.",
    "The changes could not be rolled back!": "Les changements n'ont pas pu être annulés!",
    "License for": "Licencié pour",
    "Setup": "Configuration",
    "Login*": "Se connecter*",
    "Enter your login name": "Entrez votre pseudo",
    "Enter your password": "Tapez votre mot de passe",
    "Password*": "Mot de passe*",
    "Change password": "Changer le mot de passe",
    "Retry password*": "Répéter le mot de passe*",
    "Retry your password": "Répétez votre mot de passe",
    "Easy mode": "Mode facile",
    "Normal mode": "Mode normal",
    "Admin mode": "Mode administrateur",
    "Logged in as": "Connecté en tant que",
    "in": "dans",
    "Add variable": "Ajouter une variable",
    "Variable name": "Nom de la variable",
    "Variable value": "Valeur de la variable",
    "HugoCMS Login": "HugoCMS Connexion",
    "Submit": "Soumettre",
    "Session is expired!": "Session expirée!",
    "Use template": "Utiliser le modèle",
    "Save and publish": "Sauvegarder et publier",
	"Show Front matter variables": "Afficher les matter variables",
	"Hide Front matter variables": "Masquer les matter variables",
	"Saved": "Enregistré",
    "Revert to the latest restore point. Continue?": "Revenir au dernier point de restauration. Continuer?",
    "Use minimized CSS": "Utiliser le CSS minimisé",
    "Licensee": "Licencié",
    "License key": "Clé de licence",
    "Enter the name of the licensee": "Entrez le nom du licencié",
    "Enter the license key": "Entrez la clé de licence",
    "The configuration file file does not exist.": "Le fichier de configuration n'existe pas.",
    "Cannot overwrite login data!": "Impossible d'écraser les données de connexion!",
    "The configuration file is in the wrong format.": "Le fichier de configuration est au mauvais format.",
    "Error converting configuration to JSON.": "Erreur de conversion de la configuration en JSON.",
    "Error writing updated configuration to file.": "Erreur d'écriture de la configuration mise à jour dans le fichier.",
    "Cannot save license key!": "Impossible de sauvegarder la clé de licence!",
    "Cannot save licensee data!": "Impossible de sauvegarder les données du licencié!",
    "Cannot save template!": "Impossible de sauvegarder le modèle!",
    "Project name is missing!": "Le nom du projet est manquant!",
    "A new project for a different domain are created.": "Un nouveau projet pour un autre domaine est créé.",
    "The new project cannot created!": "Le nouveau projet ne peut pas être créé!",
    "Create project*": "Créer un projet*",
    "Enter the name of the project": "Entrez le nom du projet",
    "The setup could not be performed!": "La configuration n'a pas pu être effectuée!",
    "Project directory already exists!": "Le répertoire du projet existe déjà!",
    "Project name cannot be empty!": "Le nom du projet ne peut pas être vide!",
    "Please fill out all fields with an asterisk!": "Veuillez remplir tous les champs avec un astérisque!",
    "New project/ Domain": "Nouveau projet/ Domaine",
    "Project name": "Nom du projet",
    "Please enter a project name!": "Veuillez entrer un nom de projet!",
    "Username is missing!": "Le nom d'utilisateur est manquant!",
    "License file not found!": "Fichier de licence introuvable!"
};

elFinder.prototype.i18.fr.messages.errLogout = "Session expirée!";
elFinder.prototype.i18.fr.messages['cmdcms_edit_md'] = "Ouvrir dans l'éditeur Markdown";
elFinder.prototype.i18.fr.messages['cmdcms_edit_html'] = "Ouvrir dans l'éditeur HTML";
elFinder.prototype.i18.fr.messages['untitled folder'] = 'new_folder';
elFinder.prototype.i18.fr.messages['untitled file'] = 'new_file.$1';
